### ISSUE TITLE
Tag repository

### ISSUE THREAD

**Issue by 0ssigeno** [quark-engine/quark-rules#36]
Hey guys!
I see that you are not tagging this repository when new rules are deployed, meaning that other projects that use quark engine (for example [IntelOwl](https://github.com/intelowlproject/IntelOwl)) have to lock the version on 0.0.1 or have to use the hash commit.
Is there any plan on start tagging this repo when new rules are released, like when you released the rules for [Anubis](https://twitter.com/quarkengine/status/1539528874266005505)?

**Comment by sidra-asa** [comment]
@0ssigeno

Thank you for pointing out this issue. 
Yes, it's been a while since we added tags to this repo. We will publish a new tagging version as soon as possible. 

Until we finish the release, you might want to try out a CLI tool from Quark-Engine - freshquark. It aims to help users get the latest Quark rules. You can refer to the documentation [link](https://github.com/quark-engine/quark-rules#download-rules) for more information.

We hope this information is helpful.

**Comment by 0ssigeno** [comment]
Yep, i know about  freshquark but I still prefer, when possible, to pin a version.
In this way I can prevent that every user that use IntelOwl is automatically impacted by bugs and/or vulnerability issues that may arise if I let them blindly download the latest version. (This does not only concern Quark, is a defensive approach that I try to use when developing tools).

**Comment by sidra-asa** [comment]
Yes, this may cause some unexpected bugs.
Thank you for pointing out this issue, and we will watch our repositories if there are similar issues or not.

We have already released 0.1.0, and will keep updating tagging version when new rules are added.

I will close this issue.
If you have any issues or suggestions for us, feel free to contact us.
